import { SchemaNode, FieldDefinition } from '../types';
import * as fs from 'node:fs';

export class DocGenerator {
  /**
   * Generates a markdown file documenting the schema definition structure.
   */
  static generateMD(schema: SchemaNode, outputPath: string = 'ENV_DOCS.md'): void {
    let md = '# Environment Variables Documentation\n\n';
    md += '> Documentation auto-generated by **Envium** 🚀\n\n';
    md += '| Variable | Type | Required | Default | Description |\n';
    md += '| --- | --- | --- | --- | --- |\n';
    md += DocGenerator.traverseSchemaForDocs(schema);
    
    fs.writeFileSync(outputPath, md, 'utf8');
  }

  private static traverseSchemaForDocs(schema: SchemaNode, prefix = ''): string {
    let lines = '';
    for (const key in schema) {
      if (Object.prototype.hasOwnProperty.call(schema, key)) {
        const node = schema[key];
        const fullKey = prefix ? `${prefix}_${key}` : key;
        
        if (typeof node === 'object' && node !== null && !('type' in node)) {
          lines += DocGenerator.traverseSchemaForDocs(node as SchemaNode, fullKey);
        } else {
          const def = node as FieldDefinition;
          const req = def.required ? '✅ Yes' : '❌ No';
          const defValue = def.default !== undefined ? `\`${def.default}\`` : '`-`';
          const desc = def.description || '-';
          
          lines += `| \`${fullKey}\` | \`${def.type}\` | ${req} | ${defValue} | ${desc} |\n`;
        }
      }
    }
    return lines;
  }
}
