import { SchemaNode, FieldDefinition } from '../types';
import * as fs from 'node:fs';

export class TypeGen {
  /**
   * Translates the Envium validation schema into standard TypeScript declarations.
   * Modifies both NodeJS.ProcessEnv and the Envium proxy accessor definitions.
   */
  static generate(schema: SchemaNode, outputPath: string = 'envium.d.ts'): void {
    let processEnvInterface = '';
    let proxyInterface = '';

    for (const key in schema) {
      if (Object.prototype.hasOwnProperty.call(schema, key)) {
        const node = schema[key];
        
        if (typeof node === 'object' && node !== null && !('type' in node)) {
          // Flatten property definitions for process.env (e.g. DATABASE_PORT)
          // Nest definitions for Proxy accessor (e.g. env.DATABASE.PORT)
          proxyInterface += `    ${key}: {\n`;
          for (const subKey in node) {
            const subNode = (node as SchemaNode)[subKey] as FieldDefinition;
            const tsType = TypeGen.mapType(subNode.type);
            const optional = subNode.required ? '' : '?';
            
            processEnvInterface += `      ${key}_${subKey}${optional}: string;\n`;
            proxyInterface += `      ${subKey}${optional}: ${tsType};\n`;
          }
          proxyInterface += `    };\n`;
        } else {
          // Standard root properties
          const def = node as FieldDefinition;
          const tsType = TypeGen.mapType(def.type);
          const optional = def.required ? '' : '?';
          
          processEnvInterface += `      ${key}${optional}: string;\n`;
          proxyInterface += `      ${key}${optional}: ${tsType};\n`;
        }
      }
    }

    const dtsContent = `// Auto-generated by Envium CLI 🚀
// DO NOT MODIFY DIRECTLY! This file is synced automatically.

declare namespace NodeJS {
  interface ProcessEnv {
${processEnvInterface}  }
}

declare module 'envium' {
  export interface EnvMap {
${proxyInterface}  }
  export function init(config?: any): any;
}
`;
    fs.writeFileSync(outputPath, dtsContent, 'utf8');
  }

  private static mapType(type: string): string {
    switch (type) {
      case 'number': return 'number';
      case 'boolean': return 'boolean';
      default: return 'string';
    }
  }
}
