#!/usr/bin/env node

import { DocGenerator } from './generators/DocGenerator.js';
import { ExampleGen } from './generators/ExampleGen.js';
import { NativeValidator } from './validation/NativeValidator.js';
import { Parser } from './core/Parser.js';
import * as fs from 'node:fs';
import * as path from 'node:path';

const args = process.argv.slice(2);
const command = args[0];
const isTsFlag = args.includes('--ts');

async function loadSchema() {
  const possiblePaths = [
    path.resolve(process.cwd(), 'envium.config.ts'),
    path.resolve(process.cwd(), 'envium.config.js'),
    path.resolve(process.cwd(), 'envium.config.mjs'),
    path.resolve(process.cwd(), 'envium.config.cjs')
  ];

  for (const p of possiblePaths) {
    if (fs.existsSync(p)) {
      try {
        const module = await import(`file://${p}`);
        return module.default?.schema || module.schema || module.default;
      } catch (err) {
        console.error(`[Envium] Error executing ${p}.\nIf you use native TS, remember to run this CLI with 'tsx', native types flag --experimental-strip-types in node, or transpile it first.`);
        process.exit(1);
      }
    }
  }

  console.error('❌ No envium.config.(js|ts) found.');
  console.log('💡 Run `npx envium init` first to generate a base configuration.');
  process.exit(1);
}

function normalizeParsedEnvToSchema(parsed: any): any {
  const result: any = {};

  for (const key in parsed) {
    if (!Object.prototype.hasOwnProperty.call(parsed, key)) continue;

    const value = parsed[key];

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      result[key] = normalizeParsedEnvToSchema(value);
      continue;
    }

    if (key.includes('_')) {
      const parts = key.split('_');
      let current = result;

      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];

        if (i === parts.length - 1) {
          current[part] = value;
        } else {
          if (current[part] === undefined || typeof current[part] !== 'object' || Array.isArray(current[part])) {
            current[part] = {};
          }
          current = current[part];
        }
      }
      continue;
    }

    result[key] = value;
  }

  return result;
}

async function run() {
  if (command === 'init') {
    const ext = isTsFlag ? 'ts' : 'js';
    const configPath = path.resolve(process.cwd(), `envium.config.${ext}`);
    
    if (fs.existsSync(configPath)) {
      console.log('[Envium] Configuration already exists.');
      
      const envPath = path.resolve(process.cwd(), '.env');
      if (!fs.existsSync(envPath)) {
        console.log('💡 No .env file found. Generating a template .env from existing config...');
        const schema = await loadSchema();
        ExampleGen.generate(schema, envPath);
        console.log('✅ Created .env template! Please fill in your real values.');
      }
      return;
    }
    
    let template = '';
    const envPath = path.resolve(process.cwd(), '.env');
    
    if (fs.existsSync(envPath) && fs.readFileSync(envPath, 'utf8').trim() !== '') {
      const content = fs.readFileSync(envPath, 'utf8');
      const parsed = Parser.parse(content);
      const parsedData = parsed.data || {};
      
      const buildSchemaString = (obj: any, indent = '  '): string => {
        let str = '{\n';
        for (const k in obj) {
          if (typeof obj[k] === 'object' && obj[k] !== null) {
            str += `${indent}${k}: ${buildSchemaString(obj[k], indent + '  ')},\n`;
          } else {
            const type = typeof obj[k];
            // Warning: Don't inject actual values as default for security. Just define the fields.
            str += `${indent}${k}: { type: '${type}', required: true },\n`;
          }
        }
        str += indent.slice(0, -2) + '}';
        return str;
      };
      
      const normalized = normalizeParsedEnvToSchema(parsedData);
      const schemaString = buildSchemaString(normalized);
      template = `// Envium Synchronization Schema (Autogenerated from your current .env)\nexport const schema = ${schemaString}${isTsFlag ? ' as const;' : ';'}\n`;
      console.log(`✅ Created envium.config.${ext} based on your existing .env file (Values omitted for security).`);
    } else {
      template = `// Envium Synchronization Schema
export const schema = {
  PORT: { type: 'number', required: true, default: 3000, description: 'Server port' },
  DATABASE: {
    HOST: { type: 'string', required: true, description: 'Database host url' },
    USER: { type: 'string', required: true, description: 'Database authorization user' }
  }
}${isTsFlag ? ' as const;' : ';'}\n`;
      console.log(`✅ Created envium.config.${ext} with example schema (No valid .env file detected).`);
    }

    fs.writeFileSync(configPath, template, 'utf8');
    return;
  }

  if (command === 'update') {
    const isDryRun = args.includes('--dry-run');
    const ext = isTsFlag ? 'ts' : 'js';
    const possibleConfigPaths = [
      path.resolve(process.cwd(), 'envium.config.ts'),
      path.resolve(process.cwd(), 'envium.config.js'),
      path.resolve(process.cwd(), 'envium.config.mjs'),
      path.resolve(process.cwd(), 'envium.config.cjs')
    ];

    const configPath = possibleConfigPaths.find((p) => fs.existsSync(p)) || path.resolve(process.cwd(), `envium.config.${ext}`);

    const envPath = path.resolve(process.cwd(), '.env');
    if (!fs.existsSync(envPath)) {
      console.error('❌ No .env file found to update from.');
      process.exit(1);
    }

    const content = fs.readFileSync(envPath, 'utf8');
    const parsed = Parser.parse(content);
    const parsedData = parsed.data || {};
    const normalized = normalizeParsedEnvToSchema(parsedData);

    const buildSchemaString = (obj: any, indent = '  '): string => {
      let str = '{\n';
      for (const k in obj) {
        if (typeof obj[k] === 'object' && obj[k] !== null) {
          str += `${indent}${k}: ${buildSchemaString(obj[k], indent + '  ')},\n`;
        } else {
          const type = typeof obj[k];
          str += `${indent}${k}: { type: '${type}', required: true },\n`;
        }
      }
      str += indent.slice(0, -2) + '}';
      return str;
    };

    const schemaString = buildSchemaString(normalized);
    const template = `// Envium Synchronization Schema (Autogenerated from your current .env)\nexport const schema = ${schemaString}${isTsFlag ? ' as const;' : ';'}\n`;

    if (isDryRun) {
      console.log('🔍 [dry-run] envium.config update preview (no file changes):');
      console.log(template);
      return;
    }

    fs.writeFileSync(configPath, template, 'utf8');
    console.log(`✅ Updated envium config at ${configPath} and synced new vars from .env.`);
    return;
  }

  if (command === 'gen-docs') {
    const schema = await loadSchema();
    DocGenerator.generateMD(schema);
    console.log('✅ ENV_DOCS.md synced directly from your config schema!');
    return;
  }

  if (command === 'gen-assets') {
    const schema = await loadSchema();
    ExampleGen.generate(schema);
    DocGenerator.generateMD(schema);
    console.log('🚀 .env.example and ENV_DOCS.md successfully synced from your envium.config!');
    return;
  }

  if (command === 'check') {
    const schema = await loadSchema();
    const envPath = path.resolve(process.cwd(), '.env');
    if (!fs.existsSync(envPath)) {
      console.error('❌ No .env file found to check against the schema.');
      process.exit(1);
    }
    try {
      const parseResult = Parser.parse(fs.readFileSync(envPath, 'utf8'));
      NativeValidator.validate(parseResult.data, schema);
      console.log('✅ Great! Your .env file strictly complies with the defined schema.');
    } catch (e: any) {
      console.error('❌ Schema Validation Failure:\\n', e.message);
      process.exit(1);
    }
    return;
  }

  console.log(`
  Envium CLI 🚀 - The Zero-Boilerplate Synchronization Bridge
  
  Commands:
    npx envium init [--ts]  Generate a base js or typescript configuration schema
    npx envium update [--dry-run]  Update the existing config schema from .env changes
    npx envium gen-docs     Update the ENV_DOCS.md based on your config file
    npx envium gen-assets   Sync docs and .env.example placeholders instantly
    npx envium check        Check validity of .env against your defined scheme config
  `);
}

run().catch(e => {
  console.error('[Envium] Pipeline Error:', e);
});
